### ISSUE TITLE
[BUG] TLE will be judged as WA

### ISSUE THREAD

**Issue by asef18766** [Normal-OJ/Sandbox#6]
**Describe the bug**
just like what the title said

**To Reproduce**
1. create the following C code and send it to server
```c
#include<stdio.h>
int main()
{
    while (1)
    {
        printf("do nothing :P\n");
    }
}
```

**Expected behavior**
return TLE statement

**Current Behavior**
return WA

**Comment by as535364** [comment]
maybe bogay's bug

**Comment by as535364** [comment]
it is "OLE" and be fix in recent commit
